
import { Incident, ExposureHour, ExposureKm, AppSettings, MappingRule, SGIDocument } from "../types";

export const SEED_SETTINGS: AppSettings = {
  base_if: 200000,
  base_trir: 200000,
  days_cap: 180
};

export const SEED_RULES: MappingRule[] = [
  { tipo_incidente: 'First Aid', default_recordable: false, default_lti: false, default_is_transit_laboral: false, default_is_in_itinere: false },
  { tipo_incidente: 'Medical Treatment', default_recordable: true, default_lti: false, default_is_transit_laboral: false, default_is_in_itinere: false },
  { tipo_incidente: 'Lost Time', default_recordable: true, default_lti: true, default_is_transit_laboral: false, default_is_in_itinere: false },
  { tipo_incidente: 'Fatality', default_recordable: true, default_lti: true, default_is_transit_laboral: false, default_is_in_itinere: false },
  { tipo_incidente: 'Transit', default_recordable: false, default_lti: false, default_is_transit_laboral: true, default_is_in_itinere: false },
];

// --- MASTER SGI DOCUMENTS SEED (Full Matrix ~283 Docs) ---
export const SEED_DOCUMENTS: SGIDocument[] = [
  // --- IT-SGI ---
  { code: "IT-SGI-001", title: "UTILIZACIÓN DE LLAVE DE BOCA AJUSTABLES", type: "IT", area: "SGI", objective: "Prevenir accidentes por uso de Llave de Boca Ajustable.", version: "00" },
  { code: "IT-SGI-002", title: "BOTIQUÍN DE PRIMEROS AUXILIOS", type: "IT", area: "SGI", objective: "Elementos básicos para atención de primeros auxilios.", version: "01" },
  { code: "IT-SGI-003", title: "UTILIZACIÓN Y MANTENIMIENTO DE LAVAOJOS", type: "IT", area: "SGI", objective: "Pasos básicos para utilización y mantenimiento de lavaojos.", version: "00" },
  { code: "IT-SGI-004", title: "PRIMEROS AUXILIOS", type: "IT", area: "SGI", objective: "Pasos básicos para atención de víctimas de accidente.", version: "00" },
  { code: "IT-SGI-005", title: "RESCATE EN ALTURA", type: "IT", area: "SGI", objective: "Método estándar para evacuación desde piso de enganche.", version: "01" },
  { code: "IT-SGI-006", title: "INSTRUCTIVO PLAN DE EMERGENCIA TACKER COLOMBIA", type: "IT", area: "SGI", objective: "Fortalecer capacidad de respuesta ante emergencia mayor.", version: "00" },
  { code: "IT-SGI-007", title: "GESTIÓN DE RESIDUOS METALICOS HERRAMIENTAS", type: "IT", area: "SGI", objective: "Gestión de residuos para piezas metálicas descartadas.", version: "00" },
  { code: "IT-SGI-008", title: "TRANSPORTE, CARGA Y DESCARGA DE HERRAMIENTAS", type: "IT", area: "SGI", objective: "Lineamientos para levantamiento de cargas.", version: "00" },
  { code: "IT-SGI-009", title: "METODOLOGIA DE MEJORA CONTINUA PARA LOS PROCESOS", type: "IT", area: "SGI", objective: "Datos de entrada situacionales (FODA) para mejora.", version: "00" },
  { code: "IT-SGI-011", title: "UTILIZACIÓN Y MANTENIMIENTO DEL SISTEMA ESPUMIGENO", type: "IT", area: "SGI", objective: "Utilización y mantenimiento sistema espumigeno.", version: "00" },
  { code: "IT-SGI-012", title: "SEÑALIZACIÓN, CARTELERIA Y CODIGO DE COLORES", type: "IT", area: "SGI", objective: "Cartelería y códigos de colores en el área de trabajo.", version: "00" },
  { code: "IT-SGI-013", title: "PLANIFICACION DE SIMULACROS", type: "IT", area: "SGI", objective: "Recrear situación hipotética de escenarios de emergencia.", version: "00" },
  { code: "IT-SGI-014", title: "PROTOCOLO DE PREVENCIÓN ANTE EL COVID-19", type: "IT", area: "SGI", objective: "Acciones unificadas para garantizar la salud.", version: "03" },
  { code: "IT-SGI-015", title: "SISTEMA EVACUACIÓN PIROSALVA", type: "IT", area: "SGI", objective: "Sistema para descenso controlado desde piso de enganche.", version: "00" },
  { code: "IT-SGI-016", title: "UTILIZACIÓN DE MAZA DE GOLPE", type: "IT", area: "SGI", objective: "Prevenir accidentes por uso de maza de golpe.", version: "00" },
  
  // --- IT-WSG ---
  { code: "IT-WSG-001", title: "LLAVE DE IMPACTO (SAFETY HAMMER) WIER-SPM", type: "IT", area: "WSG", objective: "Operación y mantenimiento de llave de impacto.", version: "02" },
  { code: "IT-WSG-002", title: "LLAVE DE APRIETE HYTORC XLCT", type: "IT", area: "WSG", objective: "Operación y mantenimiento de llave de apriete hidráulica.", version: "02" },
  { code: "IT-WSG-003", title: "USO DE MONTACARGAS", type: "IT", area: "WSG", objective: "Operación de Montacargas, Auto elevador, Manipulador.", version: "01" },
  { code: "IT-WSG-004", title: "TORQUES DE APRIETE PARA BULONES Y ESPARRAGOS", type: "IT", area: "WSG", objective: "Definir torques de apriete.", version: "01" },
  { code: "IT-WSG-005", title: "RECEPCIÓN Y DESCARGA DE GAS-OIL EN EL EQUIPO", type: "IT", area: "WSG", objective: "Medidas de prevención en despacho de combustible.", version: "00" },
  { code: "IT-WSG-006", title: "TUBERIAS DE ALTA PRESIÓN", type: "IT", area: "WSG", objective: "Definir tuberías para alta presión y criterios de aceptación.", version: "01" },
  { code: "IT-WSG-007", title: "USO Y CUIDADO DE GUINCHE HIDRAULICO", type: "IT", area: "WSG", objective: "Operación y mantenimiento de guinche hidráulico.", version: "00" },
  { code: "IT-WSG-008", title: "MONTAJE, DESMONTAJE Y ACONDICIONAMIENTO DE PILETAS", type: "IT", area: "WSG", objective: "Medidas preventivas en montaje de piletas.", version: "00" },
  { code: "IT-WSG-009", title: "ENCENDIDO DE FOSA DE QUEMA", type: "IT", area: "WSG", objective: "Encendido de fosa de quema en torre y flow back.", version: "01" },
  { code: "IT-WSG-010", title: "ENCENDIDO DE FOSA DE QUEMA CON PILOTO", type: "IT", area: "WSG", objective: "Encendido con piloto.", version: "03" },
  { code: "IT-WSG-011", title: "MONTAJE, DESMONTAJE Y USO DE BOP DE CORTE 10 KSI", type: "IT", area: "WSG", objective: "Uso y operación de BOP de corte.", version: "01" },
  { code: "IT-WSG-012", title: "USO Y OPERACIÓN DE CHOKE MANIFOLD 15 KSI", type: "IT", area: "WSG", objective: "Uso y operación de choke manifold.", version: "00" },
  { code: "IT-WSG-013", title: "SECUENCIA OPERATIVA DE MANIOBRAS CON STACK DE BOP", type: "IT", area: "WSG", objective: "Utilización de stack de BOP y trip tank.", version: "01" },
  { code: "IT-WSG-014", title: "ENSAYOS HIDRAULICOS DE HERMETICIDAD", type: "IT", area: "WSG", objective: "Metodología para ensayos de presión interna.", version: "00" },
  { code: "IT-WSG-015", title: "PROTOCOLO DE PRUEBA DE PERFORMANCE PARA BOP", type: "IT", area: "WSG", objective: "Ensayo de performance para BOP de corte.", version: "01" },
  { code: "IT-WSG-016", title: "MONTAJE Y DESMONTAJE DE STACK DE BOP CON PISTONES", type: "IT", area: "WSG", objective: "Montaje de Stack de BOP en Skid.", version: "01" },
  { code: "IT-WSG-017", title: "MONTAJE DE BOMBA DE TRASVASE DE FLUIDOS", type: "IT", area: "WSG", objective: "Montaje de bomba de trasvase.", version: "00" },
  { code: "IT-WSG-018", title: "MONTAJE DE GOLPEADOR EN SKID", type: "IT", area: "WSG", objective: "Montaje de Skid de golpeador.", version: "00" },
  { code: "IT-WSG-019", title: "ACONDICIONAMIENTO Y MONTAJE DE SUBESTRUCTURA TELESCOPICA", type: "IT", area: "WSG", objective: "Montaje de subestructura telescópica.", version: "02" },
  { code: "IT-WSG-020", title: "USO DE ESLINGA TPR", type: "IT", area: "WSG", objective: "Uso de eslingas para sistemas de retención temporal.", version: "00" },
  { code: "IT-WSG-021", title: "COMANDOS A DISTANCIA DE BOP", type: "IT", area: "WSG", objective: "Uso de comandos a distancia de BOP.", version: "00" },
  { code: "IT-WSG-022", title: "ARMADO DE TALLY BOOK", type: "IT", area: "WSG", objective: "Utilización del tally en armado de instalaciones.", version: "00" },
  { code: "IT-WSG-023", title: "USO DE MAN-LIFT", type: "IT", area: "WSG", objective: "Operaciones con equipo Man-Lift.", version: "01" },
  { code: "IT-WSG-024", title: "USO DE BANDEJA HIDRAULICA", type: "IT", area: "WSG", objective: "Operativa y mantenimiento de bandeja hidráulica.", version: "00" },
  { code: "IT-WSG-025", title: "FIJADO Y LIBRADO DE ANCLA DE TENSIÓN", type: "IT", area: "WSG", objective: "Fijado y librado del ancla de tensión.", version: "03" },
  { code: "IT-WSG-026", title: "MONTAJE Y DESMONTAJE DE PONY + SUB + BOP 15K", type: "IT", area: "WSG", objective: "Montaje de Pony, Subestructura y BOP 15K.", version: "01" },
  { code: "IT-WSG-027", title: "USO DE BANDEJA HIDRAULICA PERFORMANCE S.R.L.", type: "IT", area: "WSG", objective: "Uso de bandeja hidráulica Performance.", version: "00" },
  { code: "IT-WSG-028", title: "USO BOMBA DE AHOGUE TKR-05", type: "IT", area: "WSG", objective: "Uso de bomba de ahogue TKR-05.", version: "00" },
  { code: "IT-WSG-030", title: "INSPECCIÓN VISUAL DE EQUIPOS DE TORRE CAT. I Y II", type: "IT", area: "WSG", objective: "Inspecciones visuales según API RP 4G.", version: "02" },
  
  // --- IT-WPL ---
  { code: "IT-WPL-001", title: "MONTAJE Y DESMONTAJE ARBOL DE ENSAYO", type: "IT", area: "WPL", objective: "Montaje árbol.", version: "01" },
  { code: "IT-WPL-002", title: "PESCA DE VARILLA DE BOMBEO", type: "IT", area: "WPL", objective: "Pesca varilla.", version: "02" },
  { code: "IT-WPL-003", title: "SACAR TUBING DESARMANDO", type: "IT", area: "WPL", objective: "Sacar tubing.", version: "00" },
  { code: "IT-WPL-004", title: "SACAR TIRO AL PEINE", type: "IT", area: "WPL", objective: "Sacar tiro.", version: "01" },
  { code: "IT-WPL-005", title: "BAJAR TIRO DEL PEINE", type: "IT", area: "WPL", objective: "Bajar tiro.", version: "01" },
  { code: "IT-WPL-006", title: "BAJAR ARMANDO TUBULARES", type: "IT", area: "WPL", objective: "Bajar armando.", version: "01" },
  { code: "IT-WPL-007", title: "SACAR VARILLAS DE BOMBEO", type: "IT", area: "WPL", objective: "Sacar varillas.", version: "01" },
  { code: "IT-WPL-008", title: "BAJAR VARILLAS DE BOMBEO", type: "IT", area: "WPL", objective: "Bajar varillas.", version: "01" },
  { code: "IT-WPL-009", title: "USO DE PLUMA HIDROGRÚA PARA EQUIPO DE PULLING", type: "IT", area: "WPL", objective: "Uso hidrogrúa.", version: "01" },
  { code: "IT-WPL-010", title: "MONTAJE Y DESMONTAJE DE STACK DE BOP CON ASISTENCIA", type: "IT", area: "WPL", objective: "BOP con hidrogrúa.", version: "01" },
  { code: "IT-WPL-011", title: "MONTA Y DESMONTA CABEZA ROTATIVA DESDE PATIN", type: "IT", area: "WPL", objective: "Cabeza rotativa.", version: "01" },
  { code: "IT-WPL-012", title: "PH OFF-LINE DE BOP DE VARILLA DE BBEO", type: "IT", area: "WPL", objective: "PH BOP varilla.", version: "01" },
  { code: "IT-WPL-013", title: "DEJAR POZO DE PESCA CON VARILLA DE BOMBEO", type: "IT", area: "WPL", objective: "Dejar pozo pesca.", version: "01" },
  { code: "IT-WPL-014", title: "ARMADO Y PROFUNDIZADO DE BOMBA INSERTABLE", type: "IT", area: "WPL", objective: "Bomba insertable.", version: "00" },
  { code: "IT-WPL-015", title: "CALIBRAR Y REALIZAR PH DE INSTALACION CON PISTONEO", type: "IT", area: "WPL", objective: "PH con pistoneo.", version: "00" },
  { code: "IT-WPL-016", title: "REALIZADO DE MARCAS DE SEGURIDAD A CABLE DE PISTON", type: "IT", area: "WPL", objective: "Marcas cable pistón.", version: "00" },
  { code: "IT-WPL-017", title: "SACADO DE VARILLA DE BBEO. Y CAÑERIA EN SIMULTANEO", type: "IT", area: "WPL", objective: "Sacado simultáneo.", version: "00" },
  { code: "IT-WPL-018", title: "MONTAJE y DESMONTAJE DE MASTIL EQUIPO TKR 5 Y TKR 6 PULLING", type: "IT", area: "WPL", objective: "Montaje mástil.", version: "00" },
  { code: "IT-WPL-019", title: "USO DE PLUMA/HIDROGRÚA PARA EQUIPO DE PULLING", type: "IT", area: "WPL", objective: "Uso pluma.", version: "00" },
  { code: "IT-WPL-020", title: "DESMONTAJE DE EQUIPO TKR-01", type: "IT", area: "WPL", objective: "Desmontaje TKR-01.", version: "00" },
  { code: "IT-WPL-021", title: "TRANSPORTE Y MONTAJE TKR-01", type: "IT", area: "WPL", objective: "Montaje TKR-01.", version: "00" },
  { code: "IT-WPL-022", title: "PROTOCOLO DE INSPECCIÓN CRÍTICA FASE DE TRANSPORTE", type: "IT", area: "WPL", objective: "Inspección transporte.", version: "00" },

  // --- IT-WWO ---
  { code: "IT-WWO-001", title: "DESMONTAJE DE MÁSTIL MODELO H35", type: "IT", area: "WWO", objective: "Desmontaje mástil.", version: "01" },
  { code: "IT-WWO-002", title: "CARGAR, TRANSPORTAR Y DESCARGAR EQUIPAMIENTO", type: "IT", area: "WWO", objective: "Carga y descarga.", version: "01" },
  { code: "IT-WWO-003", title: "MONTAJE DE MASTIL", type: "IT", area: "WWO", objective: "Montaje mástil.", version: "01" },
  { code: "IT-WWO-006", title: "PRUEBA DE BOP Y ACUMULADOR", type: "IT", area: "WWO", objective: "Prueba acumulador.", version: "02" },
  { code: "IT-WWO-007", title: "SACAR VARILLAS DE BOMBEO", type: "IT", area: "WWO", objective: "Sacar varillas.", version: "00" },
  { code: "IT-WWO-008", title: "BAJAR VARILLAS DE BOMBEO", type: "IT", area: "WWO", objective: "Bajar varillas.", version: "00" },
  { code: "IT-WWO-009", title: "BAJAR ARMANDO TUBULARES", type: "IT", area: "WWO", objective: "Bajar armando.", version: "01" },
  { code: "IT-WWO-010", title: "SACAR TUBING DESARMANDO", type: "IT", area: "WWO", objective: "Sacar desarmando.", version: "01" },
  { code: "IT-WWO-011", title: "SACAR TIRO AL PEINE", type: "IT", area: "WWO", objective: "Sacar tiro.", version: "00" },
  { code: "IT-WWO-012", title: "BAJAR TIROS DEL PEINE", type: "IT", area: "WWO", objective: "Bajar tiro.", version: "01" },
  { code: "IT-WWO-013", title: "BAJAR PORTAMECHA ARMANDO DE PLAYA", type: "IT", area: "WWO", objective: "Bajar portamecha.", version: "00" },
  { code: "IT-WWO-014", title: "SACAR PORTAMECHA DESARMANDO A PLAYA", type: "IT", area: "WWO", objective: "Sacar portamecha.", version: "00" },
  { code: "IT-WWO-015", title: "OPERACIONES DE WIRE LINE", type: "IT", area: "WWO", objective: "Wire line.", version: "01" },
  { code: "IT-WWO-016", title: "OPERACIONES DE FRACTURA", type: "IT", area: "WWO", objective: "Fractura.", version: "01" },
  { code: "IT-WWO-017", title: "COLOCAR, OPERAR Y RETIRAR VASTAGO", type: "IT", area: "WWO", objective: "Vástago.", version: "00" },
  { code: "IT-WWO-018", title: "DESMONTAJE DE BOP, EMPAQUETADO Y PH", type: "IT", area: "WWO", objective: "Desmontaje BOP.", version: "00" },
  { code: "IT-WWO-019", title: "COLOCAR Y RETIRAR CABEZA ROTATIVA", type: "IT", area: "WWO", objective: "Cabeza rotativa.", version: "00" },
  { code: "IT-WWO-020", title: "FRENOS HIDRAULICOS TAMBOR PRINCIPAL", type: "IT", area: "WWO", objective: "Frenos hidráulicos.", version: "00" },
  { code: "IT-WWO-021", title: "POWER SWIVEL VENTURE TECH", type: "IT", area: "WWO", objective: "Power swivel.", version: "00" },
  { code: "IT-WWO-022", title: "USO Y OPERACIÓN DE TRIP TANK", type: "IT", area: "WWO", objective: "Trip tank.", version: "00" },
  { code: "IT-WWO-023", title: "CONTROL TENSION EN CABLES ACERO", type: "IT", area: "WWO", objective: "Tensión cables.", version: "01" },
  { code: "IT-WWO-024", title: "PRUEBA HIDRAULICA STACK DE BOP 10K", type: "IT", area: "WWO", objective: "PH BOP 10K.", version: "01" },
  { code: "IT-WWO-025", title: "PRUEBA HIDRAULICA STACK DE BOP 5K", type: "IT", area: "WWO", objective: "PH BOP 5K.", version: "01" },
  { code: "IT-WWO-026", title: "CONTROL DE POZO - CIERRE Y/O CORTE CON BOP 10K", type: "IT", area: "WWO", objective: "Control de pozo 10K.", version: "03" },
  { code: "IT-WWO-027", title: "PANEL CONTROL REMOTO TKR-11", type: "IT", area: "WWO", objective: "Panel BOP TKR-11.", version: "00" },
  { code: "IT-WWO-028", title: "PANEL CONTROL REMOTO TKR-08", type: "IT", area: "WWO", objective: "Panel BOP TKR-08.", version: "00" },
  { code: "IT-WWO-029", title: "PANEL CONTROL REMOTO CHOKE MANIFOLD", type: "IT", area: "WWO", objective: "Panel Choke.", version: "00" },
  { code: "IT-WWO-030", title: "ABRIR BOP TIPO U PARA CAMBIO DE SELLOS", type: "IT", area: "WWO", objective: "Cambio sellos BOP.", version: "00" },

  // --- IT-WSM ---
  { code: "IT-WSM-001", title: "TAREAS RUTINARIAS DE MANTENIMIENTO MECÁNICO", type: "IT", area: "WSM", objective: "Rutinas mecánicas.", version: "02" },
  { code: "IT-WSM-002", title: "TAREAS RUTINARIAS DE MANTENIMIENTO ELÉCTRICO", type: "IT", area: "WSM", objective: "Rutinas eléctricas.", version: "01" },
  { code: "IT-WSM-003", title: "PRUEBA DE DISYUNTORES", type: "IT", area: "WSM", objective: "Prueba de disyuntores.", version: "02" },
  { code: "IT-WSM-004", title: "FRENOS HIDRAULICOS TAMBOR PRINCIPAL", type: "IT", area: "WSM", objective: "Operación frenos.", version: "00" },
  { code: "IT-WSM-005", title: "CAMBIO DE PISTON IZAJE 1° TRAMO", type: "IT", area: "WSM", objective: "Cambio pistón izaje.", version: "00" },
  { code: "IT-WSM-006", title: "FRENOS DE ASISTENCIA A DISCO", type: "IT", area: "WSM", objective: "Freno asistencia.", version: "00" },
  { code: "IT-WSM-007", title: "FRENOS CONVENCIONALES DE TAMBOR PRINCIPAL", type: "IT", area: "WSM", objective: "Frenos convencionales.", version: "01" },
  { code: "IT-WSM-008", title: "SUMINISTRO ELÉCTRICO A OTRAS COMPAÑIAS", type: "IT", area: "WSM", objective: "Suministro eléctrico.", version: "01" },
  { code: "IT-WSM-009", title: "INSPECCION Y MANTENIMIENTO FRENOS HIDRAULICOS", type: "IT", area: "WSM", objective: "Mantenimiento frenos.", version: "00" },
  { code: "IT-WSM-010", title: "CODIFICACION DE HERRAMIENTAS", type: "IT", area: "WSM", objective: "Codificación.", version: "01" },
  { code: "IT-WSM-011", title: "MANTENIMIENTO ELECTROCOMPRESORES ATLAS COPCO", type: "IT", area: "WSM", objective: "Compresores Atlas.", version: "01" },
  { code: "IT-WSM-012", title: "INSPECCION Y MANTENIMIENTO CADENAS DE RODILLOS", type: "IT", area: "WSM", objective: "Cadenas rodillos.", version: "00" },
  { code: "IT-WSM-013", title: "TAREAS RUTINARIAS DE LUBRICACION Y ENGRASE", type: "IT", area: "WSM", objective: "Lubricación y engrase.", version: "01" },
  { code: "IT-WSM-014", title: "MANTENIMIENTO Y PRUEBA BOP DE VARILLAS", type: "IT", area: "WSM", objective: "BOP varillas.", version: "00" },
  { code: "IT-WSM-015", title: "TENDIDO Y MEDICION DE PUESTA A TIERRA", type: "IT", area: "WSM", objective: "PAT.", version: "03" },
  { code: "IT-WSM-016", title: "LUBRICACION Y ENGRASE DE VALVULAS", type: "IT", area: "WSM", objective: "Válvulas.", version: "01" },

  // --- IT-WFB / IT-CAL / IT-ING / IT-ADM ---
  { code: "IT-WFB-001", title: "CALIBRACION DE SENSORES DE APERTURA DEL CHOKE", type: "IT", area: "WFB", objective: "Sensores choke.", version: "00" },
  { code: "IT-WFB-002", title: "REPARACION DE CHOKE HIDRAULICO", type: "IT", area: "WFB", objective: "Reparación choke.", version: "00" },
  { code: "IT-WFB-003", title: "INSPECCIÓN Y MANTENIMIENTO Componentes de Alta Presión", type: "IT", area: "WFB", objective: "Componentes alta presión.", version: "02" },
  { code: "IT-WFB-004", title: "ESPECIFICACIÓN EN MEDICION DE ESPESORES DE LINEAS", type: "IT", area: "WFB", objective: "Medición espesores.", version: "00" },
  { code: "IT-WFB-005", title: "TRÁNSITO DE ACTIVOS PARA IND", type: "IT", area: "WFB", objective: "Tránsito activos.", version: "00" },
  { code: "IT-WFB-006", title: "MONTAJE Y DESMONTAJE SENSORES DE PRESION - DFIT", type: "IT", area: "WFB", objective: "Sensores DFIT.", version: "00" },
  { code: "IT-CAL-001", title: "INSPECCION Y EXTENSION DE PERIODO DE ALMACENAMIENTO DE ELASTOMEROS", type: "IT", area: "CAL", objective: "Elastómeros.", version: "00" },
  { code: "IT-ING-001", title: "CODIFICACIÓN GENERAL", type: "IT", area: "ING", objective: "Codificación productos.", version: "10" },
  { code: "IT-ING-002", title: "INSTRUCTIVO TABLA DE ESPECIFICACIONES", type: "IT", area: "ING", objective: "Tabla especificaciones.", version: "02" },
  { code: "IT-ING-003", title: "INSTRUCTIVO DE ASIGNACIÓN DE COTAS CRÍTICAS", type: "IT", area: "ING", objective: "Cotas críticas.", version: "01" },
  { code: "IT-ADM-001", title: "REALIZACIÓN y ENTREGA DE PEDIDOS", type: "IT", area: "ADM", objective: "Pedidos indumentaria.", version: "01" },
  { code: "IT-ADM-002", title: "INSTRUCTIVO DEL SISTEMA ABASTECIMIENTO", type: "IT", area: "ADM", objective: "Sistema abastecimiento.", version: "00" },

  // --- MSGI / PG ---
  { code: "MSGI-TAC-001", title: "MANUAL DEL SISTEMA DE GESTIÓN INTEGRADO", type: "MSGI", area: "TAC", objective: "Manual SGI.", version: "14" },
  { code: "PG-TAC-001", title: "CONTROL DE DOCUMENTOS Y REGISTROS", type: "PG", area: "TAC", objective: "Criterios de elaboración y control documental.", version: "12" },
  { code: "PG-TAC-002", title: "NO CONFORMIDADES, ACCIONES CORRECTIVAS", type: "PG", area: "TAC", objective: "Tratamiento de desviaciones y mejora continua.", version: "05" },
  { code: "PG-TAC-003", title: "COMPETENCIA Y FORMACIÓN", type: "PG", area: "TAC", objective: "Necesidades de entrenamiento y formación.", version: "10" },
  { code: "PG-TAC-004", title: "AUDITORÍAS INTERNAS DEL SGI", type: "PG", area: "TAC", objective: "Planificación y ejecución de auditorías.", version: "03" },
  { code: "PG-TAC-005", title: "REQUISITOS LEGALES Y OTROS", type: "PG", area: "TAC", objective: "Identificación y cumplimiento legal.", version: "04" },
  { code: "PG-TAC-006", title: "SEGUIMIENTO DE LA SATISFACCIÓN DEL CLIENTE", type: "PG", area: "TAC", objective: "Medición de expectativas y satisfacción.", version: "05" },
  { code: "PG-TAC-007", title: "PLAN ANTE CONTINGENCIAS Y EMERGENCIAS", type: "PG", area: "TAC", objective: "Prevención y respuesta ante emergencias.", version: "05" },
  { code: "PG-TAC-008", title: "IDENTIFICACIÓN DE PELIGROS Y EVALUACIÓN DE RIESGOS", type: "PG", area: "TAC", objective: "Matriz de riesgos y aspectos ambientales.", version: "04" },
  { code: "PG-TAC-009", title: "CONSULTA Y COMUNICACIÓN INTERNA Y EXTERNA", type: "PG", area: "TAC", objective: "Mecanismos de comunicación.", version: "03" },
  { code: "PG-TAC-010", title: "DESEMPEÑO, SEGUIMIENTO Y MEDICIÓN", type: "PG", area: "TAC", objective: "Seguimiento de KPIs y resultados.", version: "02" },
  { code: "PG-TAC-011", title: "PROPIEDAD DEL CLIENTE", type: "PG", area: "TAC", objective: "Protección de bienes suministrados por el cliente.", version: "02" },
  { code: "PG-TAC-012", title: "CONTROL DE PRODUCTO NO CONFORME", type: "PG", area: "TAC", objective: "Tratamiento de productos no conformes.", version: "02" },
  { code: "PG-TAC-013", title: "REVISIÓN POR LA DIRECCIÓN", type: "PG", area: "TAC", objective: "Metodología de revisión gerencial.", version: "02" },
  { code: "PG-TAC-014", title: "PLANIFICACION DE LA GESTION DE CALIDAD", type: "PG", area: "TAC", objective: "Planificación del SGC.", version: "02" },
  { code: "PG-TAC-015", title: "GESTIÓN DEL CAMBIO (MOC)", type: "PG", area: "TAC", objective: "Introducción controlada de cambios.", version: "01" },

  // --- PO-ADM / PO-COP / PO-FAB / PO-ING / PO-RHH ---
  { code: "PO-ADM-001", title: "COMPRAS", type: "PO", area: "ADM", objective: "Adquisición de bienes y servicios.", version: "04" },
  { code: "PO-ADM-002", title: "RECEPCION, MANIPULEO, ALMACENAJE Y ENTREGA", type: "PO", area: "ADM", objective: "Calidad en recepción.", version: "04" },
  { code: "PO-ADM-003", title: "ABASTECIMIENTO", type: "PO", area: "ADM", objective: "Resolución de pedidos.", version: "03" },
  { code: "PO-ADM-004", title: "EVALUACIÓN, APROBACIÓN Y DESEMPEÑO DE PROVEEDORES", type: "PO", area: "ADM", objective: "Gestión de proveedores.", version: "05" },
  { code: "PO-ADM-005", title: "PROCEDIMIENTO DE SISTEMAS", type: "PO", area: "ADM", objective: "Uso de recursos informáticos.", version: "02" },
  { code: "PO-ADM-006", title: "REVISIÓN Y DETERMINACIÓN DE LOS REQUISITOS", type: "PO", area: "ADM", objective: "Requisitos del cliente.", version: "04" },
  { code: "PO-ADM-007", title: "MANEJO DE CAJA CHICA", type: "PO", area: "ADM", objective: "Administración de caja chica.", version: "01" },
  { code: "PO-ADM-008", title: "NORMAS EN BASE CENTRAL", type: "PO", area: "ADM", objective: "Tránsito y estacionamiento en base.", version: "00" },
  { code: "PO-COP-001", title: "OPERACIONES", type: "PO", area: "COP", objective: "Prestación de servicio de alquiler.", version: "04" },
  { code: "PO-COP-002", title: "REPARACIONES", type: "PO", area: "COP", objective: "Reparación de herramientas.", version: "00" },
  { code: "PO-COP-003", title: "CONFECCION DE PROGRAMAS DE POZO", type: "PO", area: "COP", objective: "Programas operativos.", version: "00" },
  { code: "PO-FAB-001", title: "FABRICACIÓN", type: "PO", area: "FAB", objective: "Proceso de fabricación.", version: "05" },
  { code: "PO-FAB-002", title: "IDENTIFICACIÓN Y TRAZABILIDAD DE PRODUCTOS", type: "PO", area: "FAB", objective: "Trazabilidad.", version: "04" },
  { code: "PO-FAB-003", title: "PLAN DE INSPECCIÓN Y ENSAYO", type: "PO", area: "FAB", objective: "Inspección y ensayo.", version: "04" },
  { code: "PO-FAB-004", title: "EQUIPOS DE MEDICIÓN Y ENSAYO", type: "PO", area: "FAB", objective: "Calibración equipos de medición.", version: "05" },
  { code: "PO-FAB-005", title: "MANTENIMIENTO DE EQUIPOS Y MÁQUINAS", type: "PO", area: "FAB", objective: "Mantenimiento equipos de fábrica.", version: "06" },
  { code: "PO-FAB-006", title: "ENSAMBLE DE HERRAMIENTAS", type: "PO", area: "FAB", objective: "Ensamble de productos.", version: "00" },
  { code: "PO-ING-001", title: "DISEÑO Y DESARROLLO", type: "PO", area: "ING", objective: "Proceso de diseño.", version: "08" },
  { code: "PO-ING-002", title: "CONTROL DE DOCUMENTOS DE DISEÑO", type: "PO", area: "ING", objective: "Documentos técnicos.", version: "04" },
  { code: "PO-RHH-001", title: "BUSQUEDA, SELECCIÓN E INCORPORACION", type: "PO", area: "RHH", objective: "Ingreso de personal.", version: "04" },
  { code: "PO-RHH-002", title: "MANUAL DE RESPONSABILIDAD ANTE EVENTOS", type: "PO", area: "RHH", objective: "Medidas disciplinarias.", version: "00" },
  { code: "PO-RHH-003", title: "GESTION DEL DESEMPEÑO", type: "PO", area: "RHH", objective: "Evaluación de desempeño.", version: "00" },

  // --- PO-SGI ---
  { code: "PO-SGI-001", title: "INSPECCIONES Y CONTROLES", type: "PO", area: "SGI", objective: "Registros de inspecciones de instalaciones y equipos.", version: "07" },
  { code: "PO-SGI-002", title: "INVESTIGACIÓN DE INCIDENTES", type: "PO", area: "SGI", objective: "Metodología para investigación de incidentes.", version: "06" },
  { code: "PO-SGI-003", title: "GESTION DE RESIDUOS", type: "PO", area: "SGI", objective: "Gestión de residuos sólidos y líquidos.", version: "02" },
  { code: "PO-SGI-004", title: "PROGRAMA DE CONTROL MÉDICO", type: "PO", area: "SGI", objective: "Requerimientos de control de salud.", version: "02" },
  { code: "PO-SGI-005", title: "OPERACIÓN CON PRESENCIA DE GAS SULFHIDRICO (H2S)", type: "PO", area: "SGI", objective: "Medidas de seguridad con H2S.", version: "01" },
  { code: "PO-SGI-006", title: "ANALISIS DE TRABAJO SEGURO (ATS)", type: "PO", area: "SGI", objective: "Identificación de peligros antes de la tarea.", version: "02" },
  { code: "PO-SGI-007", title: "USO, MANEJO Y CONTROL DE VEHICULOS", type: "PO", area: "SGI", objective: "Políticas de uso de vehículos y manejo defensivo.", version: "08" },
  { code: "PO-SGI-008", title: "ALCOHOL Y DROGAS", type: "PO", area: "SGI", objective: "Programa de alcohol y drogas.", version: "02" },
  { code: "PO-SGI-009", title: "TAREAS OPERATIVAS CON FUERTES VIENTOS", type: "PO", area: "SGI", objective: "Límites técnicos por viento.", version: "02" },
  { code: "PO-SGI-010", title: "VISITAS GERENCIALES", type: "PO", area: "SGI", objective: "Observación de conductas por gerencia.", version: "02" },
  { code: "PO-SGI-011", title: "OBSERVACIONES CMASySO", type: "PO", area: "SGI", objective: "Observación preventiva basada en comportamiento.", version: "02" },
  { code: "PO-SGI-012", title: "USO DE ELEMENTOS DE PROTECCIÓN PERSONAL", type: "PO", area: "SGI", objective: "Uso de EPP.", version: "01" },
  { code: "PO-SGI-013", title: "INDUCCIÓN HS&E", type: "PO", area: "SGI", objective: "Inducción a ingresantes.", version: "00" },
  { code: "PO-SGI-014", title: "MONITOR DE SEGURIDAD", type: "PO", area: "SGI", objective: "Responsabilidades del monitor.", version: "00" },
  { code: "PO-SGI-015", title: "TRABAJOS EN ALTURA", type: "PO", area: "SGI", objective: "Seguridad en trabajos en altura.", version: "01" },
  { code: "PO-SGI-016", title: "PERMISO DE TRABAJO", type: "PO", area: "SGI", objective: "Sistema de permisos de trabajo.", version: "02" },
  { code: "PO-SGI-017", title: "COMPROMISO GERENCIAL", type: "PO", area: "SGI", objective: "Elementos visibles de liderazgo.", version: "00" },
  { code: "PO-SGI-018", title: "NORMAS SEGURIDAD EN TAREAS CON ENERGIA ELÉCTRICA", type: "PO", area: "SGI", objective: "Seguridad eléctrica en Workover.", version: "01" },
  { code: "PO-SGI-019", title: "RIESGO EN INSTALACIONES ELECTRICAS", type: "PO", area: "SGI", objective: "Prevención en instalaciones eléctricas.", version: "00" },
  { code: "PO-SGI-020", title: "CONSIGNACION DE EQUIPOS", type: "PO", area: "SGI", objective: "Bloqueo y etiquetado (LOTO).", version: "01" },
  { code: "PO-SGI-021", title: "MANIPULACION DE PRODUCTOS QUIMICOS", type: "PO", area: "SGI", objective: "Almacenamiento y manipuleo de químicos.", version: "01" },
  { code: "PO-SGI-022", title: "TRABAJO EN ESPACIOS CONFINADOS", type: "PO", area: "SGI", objective: "Entrada a espacios confinados.", version: "02" },
  { code: "PO-SGI-023", title: "USO Y CUIDADO DE PUENTE GRUA", type: "PO", area: "SGI", objective: "Manejo seguro de puente grúa.", version: "00" },
  { code: "PO-SGI-024", title: "MANIPULACION MANUAL DE CARGAS", type: "PO", area: "SGI", objective: "Ergonomía y levantamiento de cargas.", version: "00" },
  { code: "PO-SGI-025", title: "LINEA DE FUEGO", type: "PO", area: "SGI", objective: "Identificación de línea de fuego.", version: "01" },
  { code: "PO-SGI-026", title: "APARATOS SOMETIDOS A PRESION", type: "PO", area: "SGI", objective: "Seguridad en recipientes a presión.", version: "00" },
  { code: "PO-SGI-027", title: "OPERACIONES SIMULTANEAS (SIMOPS)", type: "PO", area: "SGI", objective: "Gestión de operaciones simultáneas.", version: "00" },
  { code: "PO-SGI-028", title: "REGLAS QUE SALVAN VIDAS", type: "PO", area: "SGI", objective: "Reglas críticas de seguridad.", version: "00" },
  { code: "PO-SGI-029", title: "SAFETY TOUR", type: "PO", area: "SGI", objective: "Recorrida de seguridad.", version: "00" },
  { code: "PO-SGI-030", title: "DOCUMENTO PUENTE", type: "PO", area: "SGI", objective: "Permisos de trabajo con operadoras.", version: "00" },

  // --- PO-WFB ---
  { code: "PO-WFB-001", title: "OPERACIONES FLOW BACK", type: "PO", area: "WFB", objective: "Limpieza de arena y sólidos.", version: "00" },
  { code: "PO-WFB-002", title: "MEDICIÓN DE ESPESORES EN LÍNEAS INTEGRALES", type: "PO", area: "WFB", objective: "Medición de espesores.", version: "02" },

  // --- PO-WPU ---
  { code: "PO-WPU-001", title: "TRANSPORTE Y MONTAJE DE EQUIPOS DE PULLING", type: "PO", area: "WPU", objective: "DTM de equipo de Pulling.", version: "03" },
  { code: "PO-WPU-002", title: "PREPARACIÓN DE BOCA DE POZO EN EQUIPOS DE PULLING", type: "PO", area: "WPU", objective: "Preparación BDP.", version: "00" },
  { code: "PO-WPU-003", title: "RETIRADO Y LIBRADO DE INSTALACIÓN DE PRODUCCIÓN", type: "PO", area: "WPU", objective: "Retirado de instalación.", version: "00" },
  { code: "PO-WPU-004", title: "ARMADO Y BAJADA DE INSTALACIÓN DE PRODUCCIÓN", type: "PO", area: "WPU", objective: "Bajada de instalación.", version: "01" },
  { code: "PO-WPU-005", title: "DESMONTAJE DE EQUIPO DE PULLING", type: "PO", area: "WPU", objective: "Desmontaje Pulling.", version: "02" },
  { code: "PO-WPU-006", title: "TAREAS ESPECIALES DE PULLING", type: "PO", area: "WPU", objective: "Tareas especiales.", version: "01" },

  // --- PO-WSG ---
  { code: "PO-WSG-001", title: "WELL SERVICE", type: "PO", area: "WSG", objective: "Metodología general de Well Service.", version: "02" },
  { code: "PO-WSG-002", title: "DESPRESURIZAR Y PURGAR POZO", type: "PO", area: "WSG", objective: "Maniobras de despresurización.", version: "03" },
  { code: "PO-WSG-003", title: "CONTROL DE Ton-MILLA", type: "PO", area: "WSG", objective: "Control de toneladas milla.", version: "03" },
  { code: "PO-WSG-004", title: "VERIFICACIÓN Y PRUEBA DEL SISTEMA ESPUMÍGENO", type: "PO", area: "WSG", objective: "Pruebas de sistema contra incendio.", version: "00" },
  { code: "PO-WSG-005", title: "CALCULAR INERCIA DEL SISTEMA DE FRENADO", type: "PO", area: "WSG", objective: "Cálculo de inercia de frenado.", version: "02" },
  { code: "PO-WSG-006", title: "USO DE HERRAMIENTAS DE POTENCIA", type: "PO", area: "WSG", objective: "Uso de herramientas en torre.", version: "00" },
  { code: "PO-WSG-007", title: "FIJADO Y LIBRADO DE CONJUNTO TAPÓN Y PACKER", type: "PO", area: "WSG", objective: "Maniobras con packer y tapón.", version: "00" },
  { code: "PO-WSG-008", title: "ROTACION DE CEMENTO O RELLENO", type: "PO", area: "WSG", objective: "Maniobras de rotación.", version: "00" },
  { code: "PO-WSG-009", title: "ENSAYO POR PISTONEO O SURGENCIA", type: "PO", area: "WSG", objective: "Ensayo por pistoneo.", version: "03" },
  { code: "PO-WSG-010", title: "ENSAYO DE LABORATORIO", type: "PO", area: "WSG", objective: "Ensayos de laboratorio en Workover.", version: "00" },
  { code: "PO-WSG-011", title: "RECEPCIÓN Y CALIBRADO DE TUBERÍA", type: "PO", area: "WSG", objective: "Manejo de tubería.", version: "00" },
  { code: "PO-WSG-012", title: "BAJAR CAÑERÍA CON HERRAMIENTAS", type: "PO", area: "WSG", objective: "Bajada de cañería.", version: "00" },
  { code: "PO-WSG-013", title: "OPERACIONES CON PRESENCIA DE H2S", type: "PO", area: "WSG", objective: "Well service con H2S.", version: "02" },
  { code: "PO-WSG-014", title: "RESCATE DE PERSONAL EN PISO DE ENGANCHE", type: "PO", area: "WSG", objective: "Evacuación desde piso de enganche.", version: "00" },
  { code: "PO-WSG-015", title: "CAMBIO DE TURNO", type: "PO", area: "WSG", objective: "Protocolo de cambio de turno.", version: "01" },
  { code: "PO-WSG-016", title: "RELEVO DE FUNCIONES", type: "PO", area: "WSG", objective: "Acreditación de relevos.", version: "01" },
  { code: "PO-WSG-017", title: "OPERACIÓN DE IZAJE", type: "PO", area: "WSG", objective: "Operaciones de izaje en equipos.", version: "01" },
  { code: "PO-WSG-018", title: "INSPECCIONES BIANUALES DE EQUIPOS DE TORRE", type: "PO", area: "WSG", objective: "Inspecciones API RP 4G.", version: "00" },
  { code: "PO-WSG-019", title: "MODIFICACIONES DEL EQUIPAMIENTO", type: "PO", area: "WSG", objective: "Cambios de diseño.", version: "00" },
  { code: "PO-WSG-020", title: "PREVENCION DE CAIDAS DE OBJETOS DESDE ALTURA", type: "PO", area: "WSG", objective: "Prevención DROPS.", version: "03" },
  { code: "PO-WSG-021", title: "AHOGUE DE POZO", type: "PO", area: "WSG", objective: "Ahogue de pozo.", version: "00" },
  { code: "PO-WSG-022", title: "USO Y CONSERVACIÓN DE ESLINGAS", type: "PO", area: "WSG", objective: "Manejo de eslingas.", version: "01" },
  { code: "PO-WSG-023", title: "CONTROL DE POZO", type: "PO", area: "WSG", objective: "Metodología de control de pozo.", version: "00" },
  { code: "PO-WSG-024", title: "CARGA Y DESCARGA CON CAMION PETROLERO", type: "PO", area: "WSG", objective: "Carga y descarga en equipos.", version: "00" },

  // --- PO-WSM ---
  { code: "PO-WSM-001", title: "POLÍTICA DE MANTENIMIENTO WELL SERVICE", type: "PO", area: "WSM", objective: "Política de mantenimiento.", version: "01" },
  { code: "PO-WSM-002", title: "MANTENIMIENTO PREVENTIVO WELL SERVICE", type: "PO", area: "WSM", objective: "Mantenimiento preventivo.", version: "02" },
  { code: "PO-WSM-003", title: "MANTENIMIENTO CORRECTIVO WELL SERVICE", type: "PO", area: "WSM", objective: "Mantenimiento correctivo.", version: "01" },
  { code: "PO-WSM-004", title: "FRENOS CONVENCIONALES DE EQUIPO", type: "PO", area: "WSM", objective: "Mantenimiento frenos convencionales.", version: "00" },
  { code: "PO-WSM-005", title: "FRENO DE ASISTENCIA TAMBOR PRINCIPAL", type: "PO", area: "WSM", objective: "Mantenimiento freno asistencia.", version: "00" },
  { code: "PO-WSM-006", title: "MAESTRO RUTINAS", type: "PO", area: "WSM", objective: "Rutinas de mantenimiento.", version: "00" },

  // --- PO-WWO ---
  { code: "PO-WWO-001", title: "TRANSPORTE Y MONTAJE DE EQUIPO DE WORKOVER", type: "PO", area: "WWO", objective: "DTM de equipo de Workover.", version: "03" },
  { code: "PO-WWO-002", title: "PREPARACIÓN, ARMADO Y PRUEBA DE BOP", type: "PO", area: "WWO", objective: "Armado y prueba de BOP.", version: "01" },
  { code: "PO-WWO-003", title: "ARMADO, BAJADO Y SACADO DE HERRAMIENTA", type: "PO", area: "WWO", objective: "Maniobras con herramienta.", version: "01" },
  { code: "PO-WWO-004", title: "PERFILAJE Y CEMENTACIÓN CORRECTIVA", type: "PO", area: "WWO", objective: "Perfilaje y cementación.", version: "01" },
  { code: "PO-WWO-005", title: "LIBRADO DE HERRAMIENTA, PESCA Y ROTACIÓN", type: "PO", area: "WWO", objective: "Pesca y rotación.", version: "01" },
  { code: "PO-WWO-006", title: "PUNZADO Y ENSAYOS", type: "PO", area: "WWO", objective: "Punzado y ensayos.", version: "01" },
  { code: "PO-WWO-007", title: "ESTIMULACIONES", type: "PO", area: "WWO", objective: "Estimulaciones en Workover.", version: "01" },
  { code: "PO-WWO-008", title: "SACADO DE HERRAMIENTA Y BAJADO DE INSTALACIÓN FINAL", type: "PO", area: "WWO", objective: "Terminación de pozo.", version: "01" },
  { code: "PO-WWO-009", title: "DESMONTAJE DE EQUIPO DE WORKOVER", type: "PO", area: "WWO", objective: "Desmontaje de equipo.", version: "02" },
  { code: "PO-WWO-010", title: "ABANDONO DEFINITIVO DE POZO", type: "PO", area: "WWO", objective: "Programas de abandono.", version: "02" },
  { code: "PO-WWO-011", title: "HERRAMIENTAS PARA TRABAJO EN TORRE", type: "PO", area: "WWO", objective: "Verificación de herramientas de torre.", version: "02" }
];

export const SEED_INCIDENTS: Incident[] = [];

// Normalized Exposure Data
export const SEED_EXPOSURE_HOURS: ExposureHour[] = [];

export const SEED_EXPOSURE_KM: ExposureKm[] = [];
